Dev example
aidtechnology/hgf-k8s-workshop pull request #1
Opened 2018-12-03 14:33 UTC by alexvicegrab

2018-12-04 23:25 UTC, nicolapaoli requested changes
All works, just a small thing to fix on commands.

2018-12-04 23:25 UTC, nicolapaoli commented on dev_example/README.md
> +    CDB_POD=$(kubectl get pods -n peers -l "app=hlf-couchdb,release=cdb-peer${NUM}" -o jsonpath="{.items[*].metadata.name}")
`$NUM` is not defined. I guess we can keep `1` for this example

2018-12-05 11:25 UTC, alexvicegrab commented on dev_example/README.md
> +    CDB_POD=$(kubectl get pods -n peers -l "app=hlf-couchdb,release=cdb-peer${NUM}" -o jsonpath="{.items[*].metadata.name}")
I will fix

2018-12-05 11:26 UTC, alexvicegrab commented on dev_example/README.md
> +    CDB_POD=$(kubectl get pods -n peers -l "app=hlf-couchdb,release=cdb-peer${NUM}" -o jsonpath="{.items[*].metadata.name}")
Fixed

2018-12-06 11:32 UTC, nicolapaoli approved these changes

2018-12-10 18:25 UTC, closed without merging